name: nightly
on:
  schedule:
    - cron: 30 * * * *
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Rustup
        run: |
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - run: cargo update
      - run: cargo build
      - run: cargo test
      - run: cargo clippy --all-targets --all-features -- --deny warnings
