name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: my_test
            name: my_test-x86_64-unknown-linux-musl.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: my_test.exe
            name: my_test-x86_64-pc-windows-msvc.zip
          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: my_test
            name: my_test-x86_64-apple-darwin.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - name: Rustup
        run: rustup update stable
      - name: Rustup target add
        if: matrix.os == 'ubuntu-latest'
        run: rustup target add ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}
      - name: Package
          shell: bash
          run: |
            strip target/${{ matrix.target }}/release/${{ matrix.bin }}
            cd target/${{ matrix.target }}/release
            if [[ "${{ matrix.os }}" == "windows-latest" ]]
            then
              7z a ../../../${{ matrix.name }} ${{ matrix.bin }}
            else
              tar czvf ../../../${{ matrix.name }} ${{ matrix.bin }}
            fi
            cd -
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'my_test*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
